[package]
name = "chess"
version = "0.1.0"
authors = ["Alex Angelini <alex.louis.angelini@gmail.com>"]

[dependencies]
clippy = "*"
futures = "0.1"
futures-cpupool = "0.1"
rand = "0.3"
time = "0.1"

[profile.release]
debug = true
